---
title: "Chicago 311 Calls Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows   
    vertical_layout: scroll
    source_code: embed
    theme: flatly
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(sf)
library(lubridate)
library(jsonlite)
library(plotly)
library(hablar)
library(RColorBrewer)

my.token <- readRDS("bevs_mapbox_token.rds")
Sys.setenv("MAPBOX_TOKEN" = my.token)

```



```{r label = "Fetch-Data", include = FALSE}

current.date <- Sys.Date()
prev.week <- (current.date - 7)

baseurl <- "https://data.cityofchicago.org/resource/v6vf-nfxy.json?$where=sr_type!='311 INFORMATION ONLY CALL' AND created_date > "

# Define a function that will fetch the 311 Service Calls data 
# each time the dashboard page is loaded in a web browser...
load_remote_data <- function() {
  
    fromJSON(readLines(URLencode(paste(baseurl, "'", prev.week, "'", "&$limit=50000",  sep = "", collapse=""))))

}

df <- load_remote_data()

# Convert coordinates to numeric...
df <- df %>%
  hablar::convert(
    dbl(latitude),
    dbl(longitude)
  )

# Remove missing values...
df <- df %>%
  filter(is.na(latitude) == FALSE)

```


Column {data-width=650}
-----------------------------------------------------------------------

### **Interactive Map of 311 Service Calls Over the Past Week**

```{r}

# Create the map...
plot_mapbox(df, lat = ~latitude, lon = ~longitude, mode = 'scattermapbox')  %>% 
  add_markers(text  = ~paste(sr_type, "\n", status),
            color = ~status, colors = c("purple", "green", "red"), size = 3000, hoverinfo = "text") %>%
  layout(
    mapbox = list(zoom = 10, center = list(lat = ~median(df$latitude), 
                                     lon = ~median(df$longitude))),
    legend = list(orientation = 'h',
              font = list(size = 8)))

```

Column {data-width=350}
-----------------------------------------------------------------------

### **Most Common Calls By Type Today**

```{r}

df.today <- df %>%
  filter(lubridate::date(created_date) == as.character(current.date))

df.counts.today <- df.today %>%
  count(sr_type) 

df.counts.top.ten.today <- df.counts.today %>%
  arrange(desc(n)) %>%
  slice_head(n = 10)

df.counts.top.ten.today %>% plot_ly(labels = ~sr_type, values = ~n) %>% 
  add_pie(hole = 0.6) %>% 
  layout(title = "",  showlegend = FALSE,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

```

### **Total Calls By Day Over the Past Week**

```{r}

# Remove time component of the date...
df <- df %>%
  mutate(created_date_only = lubridate::date(created_date))

# Count the number of calls by day...
created.date <- df %>%
  group_by(created_date_only) %>%
  count() 

# Convert to a data frame object because
# this is what plot_ly is expecting...
created.date.df <- as.data.frame(created.date)

# Ungroup the data so that the lines show up
# properly...
created.date <- created.date %>%
  ungroup()

# At long last... create the chart...
plot_ly(data = created.date.df, x = ~created_date_only, y = ~n, name = "311 Calls", type = "scatter", mode = "lines", colors = "red") %>%
  add_trace( x = ~created_date_only, y = ~n, mode = "markers", colors = "orange") %>%
  layout(title = "",
         yaxis = list(title = "Number"),
         xaxis = list(title = "Day", zeroline = TRUE),
         showlegend = FALSE)

```


### **Total Calls By Community Area Over the Past Week**

```{r}

# Count the number of calls by community area...
df.community.area <- df %>%
  group_by(community_area) %>%
  count() 

# Download the Community Area boundaries so that 
# we can use them for mapping...

ca.polys <- st_read("http://data.cityofchicago.org/api/geospatial/cauq-8yn6?method=export&format=GeoJSON", quiet = TRUE)

# Use an inner join from dplyr to link the 311 
# call tallys to the polygons...
ca.polys.tb <- inner_join(df.community.area, ca.polys,by = c("community_area" = "area_numbe"))

# Create the bar chart!
plot_ly(data = ca.polys.tb, x = ~community_area, y = ~n, type = 'bar', 
        name = 'Calls By CCA', 
        text = ~paste("Total of ", n, "calls this week in", stringr::str_to_title(ca.polys.tb$community)), 
                     color = I("orange")) %>% 
layout(title = "",
       xaxis = list(title = "", showticklabels = FALSE),
       yaxis = list(title = ""))


```

